import numpy as np

FRAME_TIME = 1 / 60
MAX_STEPS = 1000

GRAVITY_X = 0
GRAVITY_Y = 0
GRAVITY_Z = -9.8

BACK_LEG_AMPLITUDE = np.pi / 4
BACK_LEG_FREQUENCY = 10
BACK_LEG_PHASE = -np.pi / 8
FRONT_LEG_AMPLITUDE = np.pi / 8
FRONT_LEG_FREQUENCY = 20
FRONT_LEG_PHASE = 0

LEG_STRENGTH = 20

GENERATION_COUNT = 10